name: Daily Commit

on:
  schedule:
    - cron: '37 8 * * *'  # Every day at 3pm UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make Daily Commit
        run: |
          echo "// Commit made on $(date -u)" >> daily.js
          git add daily.js
          git commit -m "Daily commit $(date -u)" || echo "No changes to commit"
          git push
